"""CONTRACT: the frozen CORE_CODE_SHA256 matches the core source.

`instrument/_core_provenance.py` is generated by `tools/build_core_hash.py`.
If any core file (kernel / reading / lexicons) changes without regenerating
it, the emission provenance would pin the wrong algorithm. This wraps the
build tool's `--check` so that drift is a CI failure (mirrors how
`test_layering` wraps `check_layers`).

If it fails: `python -m tools.build_core_hash` and commit the regenerated
module.
"""
from __future__ import annotations

from tools.build_core_hash import check


def test_core_code_hash_matches_source():
    assert check() == 0, (
        "CORE_CODE_SHA256 is stale — regenerate with "
        "`python -m tools.build_core_hash`"
    )
