"""auto-generated by tools/build_catalog.py — DO NOT HAND-EDIT.

Edit the source JSON at
    _data/emissions_catalog/v2.json
and re-run:

    python -m tools.build_catalog --version v2

Runtime is pure: no file I/O, no env reads.
"""

from __future__ import annotations

CATALOG: dict = { '_comment': [ 'Emissions catalog — v2.',
                '',
                'Supersedes the v1 metrics catalog. The emission surface is now',
                'four-part: register, arc, flags, coherence. Per-slice labels and',
                'flag detectors are parameterised here; code contains detection',
                'logic only.',
                '',
                'v2 thresholds are PRE-CALIBRATION placeholders, checked against',
                "the 515-trace LLM-output corpus to ensure they don't false-positive-",
                'flood on normal prose but not yet empirically tuned. The planned',
                'calibration corpus (thousands of LLM outputs across two',
                'temperatures via free models) will feed v3 catalog publication.',
                '',
                "Each detector's parameters are documented at its registration site",
                'in shaper/metrology/emissions/detectors/{slice_labels,flags}.py.',
                'Renaming a label, moving a threshold, adding a flag to the catalog',
                'are all JSON-only changes. Registering a new detector requires a',
                'code change + a catalog bump.'],
  'arc': { 'slice_labels': [ {'detector': 'opening', 'id': 'opening'},
                             {'detector': 'closing', 'id': 'closing'},
                             { 'detector': 'introduction',
                               'id': 'introduction',
                               'params': {'min_novelty': 0.5}},
                             { 'detector': 'elaboration',
                               'id': 'elaboration',
                               'params': {'max_novelty': 0.5, 'min_novelty': 0.2}},
                             { 'detector': 'plateau',
                               'id': 'plateau',
                               'params': {'max_novelty': 0.2}},
                             {'detector': 'reopen', 'id': 'reopen', 'params': {'min_delta': 0.15}},
                             { 'detector': 'variance_burst',
                               'id': 'variance_burst',
                               'params': {'min_absolute': 300.0, 'min_ratio': 2.0}},
                             { 'detector': 'negation_cluster',
                               'id': 'negation_cluster',
                               'params': {'min_absolute': 0.1, 'min_ratio': 2.0}},
                             { 'detector': 'hedging_peak',
                               'id': 'hedging_peak',
                               'params': {'min_absolute': 0.5}}]},
  'calibration_state': 'pre-calibration placeholders; empirical tuning planned on synthetic corpus',
  'coherence': { 'bands': [ {'label': 'high', 'min': 0.8},
                            {'label': 'moderate', 'min': 0.5},
                            {'label': 'low', 'min': None}]},
  'deviation_overlay': { 'bands': [ {'label': 'within_spec', 'max': 1.25},
                                    {'label': 'notable', 'max': 1.52},
                                    {'label': 'extreme', 'max': None}],
                         'flag_threshold_std': 2.0},
  'flags': [ { 'detector': 'novelty_reopen',
               'id': 'novelty_reopen',
               'params': {'min_delta': 0.15},
               'severity': 'notable'},
             { 'detector': 'novelty_collapse',
               'id': 'novelty_collapse',
               'params': {'max_novelty': 0.1, 'min_consecutive': 2},
               'severity': 'notable'},
             { 'detector': 'variance_spike',
               'id': 'variance_spike',
               'params': {'min_absolute': 300.0, 'min_ratio': 2.0},
               'severity': 'notable'},
             { 'detector': 'modal_pivot',
               'id': 'modal_pivot',
               'params': {'min_swing': 0.3},
               'severity': 'notable'},
             { 'detector': 'negation_cluster',
               'id': 'negation_cluster',
               'params': {'min_absolute': 0.1, 'min_ratio': 2.0},
               'severity': 'notable'},
             { 'detector': 'register_shift',
               'id': 'register_shift',
               'params': {'min_ratio': 2.0},
               'severity': 'notable'},
             { 'detector': 'malformed_fence_recovered',
               'id': 'malformed_fence_recovered',
               'severity': 'critical'},
             { 'detector': 'unbalanced_quotation',
               'id': 'unbalanced_quotation',
               'severity': 'notable'},
             { 'detector': 'below_envelope_shaper',
               'id': 'below_envelope_shaper',
               'params': {'min_words': 150},
               'severity': 'critical'},
             { 'detector': 'trajectory_unmeasurable',
               'id': 'trajectory_unmeasurable',
               'params': {'min_slices': 2},
               'severity': 'critical'},
             {'detector': 'cross_view_diverge', 'id': 'cross_view_diverge', 'severity': 'notable'},
             { 'detector': 'feature_unmeasurable_cluster',
               'id': 'feature_unmeasurable_cluster',
               'params': {'min_count': 5},
               'severity': 'critical'}],
  'instrument_version': '0.9.1',
  'pair_overlay': { 'bands': [ {'label': 'break', 'max': 0.7},
                               {'label': 'drift', 'max': 0.85},
                               {'label': 'stable', 'max': None}]},
  'register': { '_comment': [ 'Register labels come from two sources:',
                              '1. Distance bands, when the reading projects onto a reference '
                              'cohort.',
                              '   Walked in order; first band whose max is not exceeded wins.',
                              '2. Projection states, when projection fails. Emitted by the',
                              "   emissions API as a graceful-degradation fallback. 'structural'",
                              '   for table-dominated documents that have no prose-cohort match;',
                              "   'unprojectable' for everything else that fails.",
                              '',
                              'When a projection-state label fires, the register.evidence block',
                              "carries 'unprojectable_subtype' naming one of the four taxonomy",
                              'values below. The shape of the emission is the same whether the',
                              'label came from a band or a projection state — same four-part',
                              'DocumentEmission, with register.distance = null on degraded cases.'],
                'bands': [ {'label': 'match', 'max': 2.3},
                           {'label': 'drift', 'max': 2.8},
                           {'label': 'break', 'max': None}],
                'projection_states': [ { 'description': 'Content IS structure (table-dominated). '
                                                        'Prose residue below envelope; no '
                                                        'prose-cohort reference matches. Evidence '
                                                        'carries '
                                                        "unprojectable_subtype='reference_table' "
                                                        'and a structural_profile dict.',
                                         'label': 'structural'},
                                       { 'description': "Document doesn't project onto any "
                                                        "reference's PC space. Evidence carries "
                                                        'unprojectable_subtype naming why '
                                                        '(instruction_format / mixed_structural_fp '
                                                        '/ insufficient_prose) and a '
                                                        'structural_profile dict.',
                                         'label': 'unprojectable'}],
                'unprojectable_subtypes': [ { 'description': 'Tables dominate (table_ratio > 0.50) '
                                                             'and prose residue < envelope.',
                                              'id': 'reference_table',
                                              'surfaced_as_label': 'structural'},
                                            { 'description': 'Code/list scaffolding dominates '
                                                             '(structure_ratio > 0.40) but prose '
                                                             'residue is between 100 and 300 '
                                                             'words. Emissions attempts '
                                                             'aggressive-scaffolding-strip '
                                                             'recovery before emitting; succeeds '
                                                             'when stripped residue clears the '
                                                             '150-word envelope. On recovery, '
                                                             'evidence carries '
                                                             "preprocessed='aggressive_scaffolding_strip'.",
                                              'id': 'instruction_format',
                                              'surfaced_as_label': 'unprojectable'},
                                            { 'description': 'Safety-net label: prose_words >= 300 '
                                                             'AND structure_ratio < 0.50. These '
                                                             'should have projected on the normal '
                                                             'path; if they reach here, the router '
                                                             'rejected them anyway.',
                                              'id': 'mixed_structural_fp',
                                              'surfaced_as_label': 'unprojectable'},
                                            { 'description': 'Genuinely too little prose to '
                                                             'project on any reference. No '
                                                             'recovery available.',
                                              'id': 'insufficient_prose',
                                              'surfaced_as_label': 'unprojectable'}]},
  'schema_version': '0.9.1',
  'status': 'draft',
  'version': 'v2'}

SOURCE_SHA256: str = "e040613dfb47cab55a5d80fc2b0d7bf64e1e3a597071a31cbf6c6bcb6dcab97d"
