"""auto-generated by tools/build_core_hash.py — DO NOT HAND-EDIT.

CORE_CODE_SHA256 is a content hash over the measurement core source
(kernel + reading + lexicons), newline-normalised and path-sorted. It pins
the exact measurement algorithm in emission provenance. Regenerate after any
core code change:

    python -m tools.build_core_hash
"""

from __future__ import annotations


CORE_FILE_SHA256: dict[str, str] = {
    "instrument/kernel/__init__.py": "de867690f1a90588626a9581841dfd93667969fd61a881078469778b2cf68712",
    "instrument/kernel/cleaning.py": "6a560ce5feeb80dd9bcd14c55dc083718c358c7dfef23e8915d166f2e52a6842",
    "instrument/kernel/compress.py": "3cb12ab50bdfcbde0758e0be8f68cb103284d09a02f358b1e4b98da84a860683",
    "instrument/kernel/detrandom.py": "3b2a880dacd8e7bf34a05799748f2eb1f1c0c0a07df298c7d719fc4796fe9e35",
    "instrument/kernel/distance.py": "130a4bc57e6433e511eba17d2b69618d35048485f70a49eb3646722d8a86721d",
    "instrument/kernel/features/__init__.py": "b6063adcea0f3975191932481e02a617b8e14e187acad1cede9a872d5c6f7ce2",
    "instrument/kernel/features/cohesion.py": "bff4f9600c586ebd06bf26abbc15b462427b218dbd2a3c44c907f513abe37a7d",
    "instrument/kernel/features/register.py": "068d567c0e7606d6da7bc93764859a2bcf42ee84725077b91cf49476ff4d3c19",
    "instrument/kernel/features/rst.py": "bfc860f28607e538ea200d6c293d8a994a7779437e0f4a41780efa4172412a66",
    "instrument/kernel/features/sfl.py": "297e322afee9841033155ed23beebef37eb6b54326d2aacd19cd080fc44350b7",
    "instrument/kernel/features/stylometry.py": "ba24c976d83a0d64b2a80b4c10390df4d94f325527ed05529a0b7d6206a4091f",
    "instrument/kernel/features/trajectory_features.py": "75b5ea68eecee52627c4c652c21a778e4ea92b3c55ca70390639de09339d8982",
    "instrument/kernel/grid.py": "2a52b94717c57af0156286a68bab0cf2f52a19e345d0260a1f4e18a157a697d1",
    "instrument/kernel/nanmath.py": "2243e997ae979296ebd10c957366a862f5e1aed7037a477ac339984f444a0bf3",
    "instrument/kernel/paragraphs.py": "ee12fb4c838e5afc13771fd06c0357cb36dd135f12caddf31693afe7c0ae6120",
    "instrument/kernel/quantize.py": "f18b870602fe123eddb3dc444bf9e695b6ee9fe00144bcfac531f367aa546be4",
    "instrument/kernel/regimes.py": "657c8e7dbf3afb0a48228ebe11500afcb1caf848176f357c27cab93ccfa59188",
    "instrument/kernel/scripts.py": "0e0b6703a03801936b699a9f637bfa649f0622e2a59124e628467d6312bae909",
    "instrument/kernel/sentences.py": "2dd250d2cf673d224977e4ebc8c1d35617547e8de26ac81d1531298c536c32c9",
    "instrument/kernel/slicer.py": "5aaf9ab873983d08164b0021782e0a0eaa2774d877172a642599a59ba1a77a2e",
    "instrument/kernel/stats.py": "31709efe1772d13465c644041c390f54fd55436db942a95b5480a1b15afedd36",
    "instrument/kernel/tokens.py": "fc806e33e28909c9e7c60f95ac08b449a3ca6decbd42faeac278249451c3f597",
    "instrument/lexicons/__init__.py": "74050ed25c9d3f13338a9db1e3824da8647938c24ac7c33bf37de81f9c2b60e3",
    "instrument/lexicons/_v1.py": "4ee9ec4b38e7f53c98f8c09fc5ef611c54f9f605755cd358717f120ab74dd0f0",
    "instrument/reading/__init__.py": "06f49408e8f16ce53c50dee316ccbd8123912930acad0702e03a4f035ca30f99",
    "instrument/reading/bootstrap.py": "f31acba2d876828d8eb4479fc85dddfbd81717f7f7e9f1ffdb5946f84634e01f",
    "instrument/reading/convergence.py": "9a826d38a1b4ca3c813e2deb5b8a122c2044a9f6971161b325f9e665fe2e2c30",
    "instrument/reading/distributional.py": "beb4c1563400be9319b1b87df89733459aee9f16a5da101ff970266f0c60edb9",
    "instrument/reading/document.py": "06ed175d295aba2fe9adf92620879a1b9369345c90913793f994f238c5c811b2",
    "instrument/reading/embedder.py": "91e3e62948645399fd10a6fd0b56b649b75bb2dc75f462b157e7915bfa479872",
    "instrument/reading/extended/__init__.py": "9acd1bfe325c39cbb01b137c6834a50b50255212e9439025b390c65deec7cdcf",
    "instrument/reading/extended/cohesion.py": "34aa5b822000d1fb64817df80cd55799af46eb0cc9dfff32c56750aaad018d6b",
    "instrument/reading/extended/feature.py": "973c97d1561045b5aefd18c25549239f335fdbb77dc70012ca6e99c10581ced4",
    "instrument/reading/extended/lexicons.py": "dc48a2cf4b6e33e46378daccab4509fda1cc49be52cd75faa928aad654addbb3",
    "instrument/reading/extended/rst.py": "ccb2031d2ef5a82c9cc1755d132a0737430d8b3039f3528e09cc19f865d53bc7",
    "instrument/reading/extended/sfl.py": "b69055b17996a9c34d8c8005756c3cfaf2fa2a18e3329bebac35622b21f5820e",
    "instrument/reading/flat.py": "21da0f366486eb7a9e75c6250a2e61d24c0ca635fe844ed45d237623028ff4cc",
    "instrument/reading/joint.py": "e520b681c73d68e6da2a110c97027b0d716bfca80d7bb223eca2db9b9c14d1a0",
}

CORE_CODE_SHA256: str = "cc207254d437a6161f5185cd4777b09aa9ef3ae7af577cd57ce76ec183756fe8"
