"""build_core_hash — freeze a content hash of the measurement core.

The core (`instrument.kernel`, `instrument.reading`, `instrument.lexicons`)
is the pure measurement procedure. `instrument_version` is a human-assigned
string — an assertion. `CORE_CODE_SHA256` is a *proof*: a hash over the core
source, so an emission's provenance pins the exact algorithm (including
frozen decision constants such as convergence's `AGREE_TOLERANCE`) that
produced it.

Determinism / portability:
  - newline-normalised (\\r\\n, \\r -> \\n) so checkout line-ending policy
    does not change the hash;
  - sorted by POSIX relative path;
  - tests, __pycache__, and this generated module are excluded.

The hash is frozen into `instrument/_core_provenance.py` and consumed at L4
(`emit`) — never computed inside the core, so the core stays I/O-free.

    python -m tools.build_core_hash
    python -m tools.build_core_hash --check
"""
from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
INSTRUMENT = REPO_ROOT / "instrument"
CORE_PACKAGES = ("kernel", "reading", "lexicons")
OUTPUT = INSTRUMENT / "_core_provenance.py"

HEADER = '''"""auto-generated by tools/build_core_hash.py — DO NOT HAND-EDIT.

CORE_CODE_SHA256 is a content hash over the measurement core source
(kernel + reading + lexicons), newline-normalised and path-sorted. It pins
the exact measurement algorithm in emission provenance. Regenerate after any
core code change:

    python -m tools.build_core_hash
"""

from __future__ import annotations

'''


def _core_files() -> list[Path]:
    files: list[Path] = []
    for pkg in CORE_PACKAGES:
        for p in (INSTRUMENT / pkg).rglob("*.py"):
            if "tests" in p.parts or "__pycache__" in p.parts:
                continue
            files.append(p)
    return sorted(files, key=lambda p: p.relative_to(REPO_ROOT).as_posix())


def _file_sha(p: Path) -> str:
    text = p.read_text(encoding="utf-8")
    normalised = text.replace("\r\n", "\n").replace("\r", "\n")
    return hashlib.sha256(normalised.encode("utf-8")).hexdigest()


def compute() -> tuple[str, list[tuple[str, str]]]:
    manifest: list[tuple[str, str]] = []
    for p in _core_files():
        rel = p.relative_to(REPO_ROOT).as_posix()
        manifest.append((rel, _file_sha(p)))
    rolled = "\n".join(f"{rel} {sha}" for rel, sha in manifest)
    core_sha = hashlib.sha256(rolled.encode("utf-8")).hexdigest()
    return core_sha, manifest


def render() -> str:
    core_sha, manifest = compute()
    lines = [HEADER, "CORE_FILE_SHA256: dict[str, str] = {"]
    for rel, sha in manifest:
        lines.append(f'    "{rel}": "{sha}",')
    lines.append("}")
    lines.append("")
    lines.append(f'CORE_CODE_SHA256: str = "{core_sha}"')
    lines.append("")
    return "\n".join(lines)


def check() -> int:
    expected = render()
    if not OUTPUT.exists():
        print(f"{OUTPUT.relative_to(REPO_ROOT)}: missing", file=sys.stderr)
        return 1
    if OUTPUT.read_text(encoding="utf-8") != expected:
        print(
            f"{OUTPUT.relative_to(REPO_ROOT)}: drift — regenerate with "
            f"`python -m tools.build_core_hash`",
            file=sys.stderr,
        )
        return 1
    print(f"{OUTPUT.relative_to(REPO_ROOT)}: ok")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    if args.check:
        return check()
    OUTPUT.write_text(render(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
