"""build_lexicons — JSON lexicon tree → instrument/lexicons/_v<N>.py.

Deterministic: same JSON tree → byte-identical .py module. No
timestamps, no hostname, no environment strings in the output.

Invocation:
    python -m tools.build_lexicons --version v1
    python -m tools.build_lexicons --check

The generated module exposes:
    LEXICONS: dict[str, frozenset[str]]      keyed by "<dir>_<name>"
    MANIFEST: dict[str, dict]                 sha256 + count per key
    BODY_SHA256: str                          attestation over the LEXICONS literal

Consumers import:
    from instrument.lexicons import LEXICONS
    material_verbs = LEXICONS["processes_material"]
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "_data" / "lexicons"
OUTPUT_ROOT = REPO_ROOT / "instrument" / "lexicons"

HEADER = '''"""auto-generated by tools/build_lexicons.py — DO NOT HAND-EDIT.

Edit the source JSON under lexicons/v{version_no}/ and re-run:

    python -m tools.build_lexicons --version v{version_no}

Runtime is pure: no file I/O, no env reads, no caches required.
"""

from __future__ import annotations

'''


def _key_from_path(rel: Path) -> str:
    parts = rel.with_suffix("").parts
    return "_".join(parts)


def _load_entries(path: Path) -> frozenset[str]:
    data = json.loads(path.read_text(encoding="utf-8"))
    words = data.get("words")
    if not isinstance(words, list):
        raise ValueError(f"{path}: missing 'words' list")
    return frozenset(
        entry["word"].strip().lower()
        for entry in words
        if isinstance(entry, dict) and "word" in entry
    )


def _render_frozenset(key: str, items: frozenset[str]) -> str:
    ordered = sorted(items)
    pieces = ",\n        ".join(repr(w) for w in ordered)
    return f'    "{key}": frozenset((\n        {pieces},\n    )),'


def _render_manifest(manifest: dict[str, dict]) -> str:
    lines = ["MANIFEST: dict[str, dict] = {"]
    for key in sorted(manifest):
        entry = manifest[key]
        lines.append(
            f'    "{key}": '
            f'{{"sha256": "{entry["sha256"]}", "count": {entry["count"]}}},'
        )
    lines.append("}")
    return "\n".join(lines)


def build(version: str) -> str:
    src = SOURCE_ROOT / version
    if not src.is_dir():
        raise SystemExit(f"source tree missing: {src}")

    json_files = sorted(p for p in src.rglob("*.json") if p.name != "manifest.json")
    if not json_files:
        raise SystemExit(f"no json files under {src}")

    lexicons: dict[str, frozenset[str]] = {}
    manifest: dict[str, dict] = {}
    for path in json_files:
        key = _key_from_path(path.relative_to(src))
        words = _load_entries(path)
        lexicons[key] = words
        raw = path.read_bytes()
        manifest[key] = {
            "sha256": hashlib.sha256(raw).hexdigest(),
            "count": len(words),
        }

    body_lines = ["LEXICONS: dict[str, frozenset[str]] = {"]
    for key in sorted(lexicons):
        body_lines.append(_render_frozenset(key, lexicons[key]))
    body_lines.append("}")
    body = "\n".join(body_lines)
    body_sha = hashlib.sha256(body.encode("utf-8")).hexdigest()

    version_no = version.lstrip("v")
    parts = [
        HEADER.format(version_no=version_no),
        body,
        "",
        _render_manifest(manifest),
        "",
        f'BODY_SHA256: str = "{body_sha}"',
        "",
    ]
    return "\n".join(parts)


def write(version: str) -> Path:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    out = OUTPUT_ROOT / f"_{version}.py"
    out.write_text(build(version), encoding="utf-8")
    return out


def check(version: str) -> int:
    expected = build(version)
    out = OUTPUT_ROOT / f"_{version}.py"
    if not out.exists():
        print(f"{out.relative_to(REPO_ROOT)}: missing", file=sys.stderr)
        return 1
    actual = out.read_text(encoding="utf-8")
    if actual != expected:
        print(
            f"{out.relative_to(REPO_ROOT)}: drift — regenerate with "
            f"`python -m tools.build_lexicons --version {version}`",
            file=sys.stderr,
        )
        return 1
    print(f"{out.relative_to(REPO_ROOT)}: ok")
    return 0


def check_data_manifest(version: str) -> int:
    """Validate the standalone `_data/.../manifest.json` against the files.

    SECURITY.md points auditors at this manifest for provenance. It is a
    separate artifact from the MANIFEST embedded in the compiled module, so
    it can drift when source JSONs are edited without regeneration. This
    guard recomputes every per-file sha256 + count (using the same dedup as
    the build) and the total, and fails on any mismatch.
    """
    src = SOURCE_ROOT / version
    man_path = src / "manifest.json"
    if not man_path.exists():
        print(f"{man_path}: missing", file=sys.stderr)
        return 1
    man = json.loads(man_path.read_text(encoding="utf-8"))
    problems: list[str] = []
    total = 0
    for rel, meta in man.get("files", {}).items():
        p = src / rel
        if not p.exists():
            problems.append(f"{rel}: file missing")
            continue
        sha = hashlib.sha256(p.read_bytes()).hexdigest()
        count = len(_load_entries(p))
        total += count
        if meta.get("sha256") != sha:
            problems.append(f"{rel}: sha256 mismatch")
        if meta.get("count") != count:
            problems.append(f"{rel}: count {meta.get('count')} != {count}")
    if man.get("total_entries") != total:
        problems.append(f"total_entries {man.get('total_entries')} != {total}")
    if problems:
        for pr in problems:
            print(f"_data manifest: {pr}", file=sys.stderr)
        return 1
    print(f"{man_path.relative_to(REPO_ROOT)}: ok")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="v1")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    if args.check:
        # Fail if either the compiled module or the standalone manifest drifts.
        return check(args.version) or check_data_manifest(args.version)
    out = write(args.version)
    print(f"wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
