"""build_catalog — JSON catalog → instrument/emissions/catalog_v<N>.py.

Deterministic: same JSON → byte-identical `.py` module. No file
I/O at runtime: readers do `from instrument.emissions.catalog_v2
import CATALOG`.

Invocation:
    python -m tools.build_catalog --version v2
    python -m tools.build_catalog --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from pprint import pformat

REPO_ROOT = Path(__file__).resolve().parents[1]
SOURCE_ROOT = REPO_ROOT / "_data" / "emissions_catalog"
OUTPUT_ROOT = REPO_ROOT / "instrument" / "emissions"

HEADER = '''"""auto-generated by tools/build_catalog.py — DO NOT HAND-EDIT.

Edit the source JSON at
    _data/emissions_catalog/{version}.json
and re-run:

    python -m tools.build_catalog --version {version}

Runtime is pure: no file I/O, no env reads.
"""

from __future__ import annotations

'''


def build(version: str) -> str:
    src = SOURCE_ROOT / f"{version}.json"
    if not src.exists():
        raise SystemExit(f"source json missing: {src}")
    data = json.loads(src.read_text(encoding="utf-8"))
    sha = hashlib.sha256(src.read_bytes()).hexdigest()
    body = pformat(data, indent=2, sort_dicts=True, width=100)
    return (
        HEADER.format(version=version)
        + f"CATALOG: dict = {body}\n"
        + f'\nSOURCE_SHA256: str = "{sha}"\n'
    )


def write(version: str) -> Path:
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    out = OUTPUT_ROOT / f"catalog_{version}.py"
    out.write_text(build(version), encoding="utf-8")
    return out


def check(version: str) -> int:
    expected = build(version)
    out = OUTPUT_ROOT / f"catalog_{version}.py"
    if not out.exists():
        print(f"{out.relative_to(REPO_ROOT)}: missing", file=sys.stderr)
        return 1
    actual = out.read_text(encoding="utf-8")
    if actual != expected:
        print(
            f"{out.relative_to(REPO_ROOT)}: drift — regenerate with "
            f"`python -m tools.build_catalog --version {version}`",
            file=sys.stderr,
        )
        return 1
    print(f"{out.relative_to(REPO_ROOT)}: ok")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--version", default="v2")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    if args.check:
        return check(args.version)
    out = write(args.version)
    print(f"wrote {out.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
